name: Build and Security Scan

on:
  push:
    branches:
    - main
    - '!master'
  pull_request:
    branches:
    - main
    - '!master'
  
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v4
      - name: list files
        run: |
          ls -al


